name: "yolo-608"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "data"
    data_type: TYPE_FP32
    dims: [ 3, 608, 608 ]
  }
]
output [
  {
    name: "prob"
    data_type: TYPE_FP32
    dims: [ 7001, 1, 1 ]
  }
]
dynamic_batching {}