version: '2.3'

services:

  yolo:
    image: openmpf/openmpf_ocv_yolo_detection

    shm_size: '1gb'

    ipc: host

    environment:
      MPF_LOG_PATH: .
      THIS_MPF_NODE: .

    volumes:
      - $PWD/test:/test

    command: [runner, --daemon]

  triton:
    image: nvcr.io/nvidia/tritonserver:21.06-py3

    # shared memory size
    shm_size: '1gb'

    # interprocess communication (or use shm bind volume)
    ipc: host

    ulimits:
      memlock: -1
      stack: 67108864

    runtime: nvidia

    ports:
    - "8000:8000"  # http management port
    - "8001:8001"  # server GRPC port
    - "8002:8002"  # metrics server port

    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - LD_PRELOAD=/plugins/liblayerplugin.so

    volumes:
      # change these as needed
      - "/mnt/data/docker/triton/models/yolov4-416:/models/yolo-416"
      - "/mnt/data/docker/triton/plugins/liblayerplugin.so.r21.06-416:/plugins/liblayerplugin.so"
     # volume for shared memory
     # - "/dev/shm:/dev/shm"

    command: [tritonserver,--model-repository=/models,
                          --strict-model-config=false,
                          --model-control-mode=explicit,
                          --load-model=yolo-416,
                          # --log-verbose=1,
                          --grpc-infer-allocation-pool-size=16]
