
ISO6393_2_BCP47 = dict(
    AMH=["am-ET"],
    ARA=["ar-SA", "ar-EG", "ar-IQ", "ar-IL", "ar-AE", "ar-SY", "ar-LY", "ar-DZ",
         "ar-BH", "ar-JO", "ar-KW", "ar-LB", "ar-MA", "ar-OM", "ar-PS", "ar-QA",
         "ar-TN", "ar-YE"],
    # AZE=["az-AZ"],
    # BEL=["be-BY"],
    # BEN=["bn-BD", "bn-IN"],
    # BOD=["bo"], # Deprecated
    BUL=["bg-BG"],
    # CEB=["ceb"],
    CES=["cs-CZ"],
    CMN=["zh-CN"],
    ELL=["el-GR"],
    ENG=["en-US", "en-CA", "en-GB", "en-AU", "en-GH", "en-HK", "en-IN", "en-IE",
         "en-KE", "en-NZ", "en-NG", "en-PH", "en-SG", "en-ZA", "en-TZ"],
    FRA=["fr-FR", "fr-CA", "fr-CH"],
    # GUG=["gn"], # Deprecated
    # HAT=[],
    # HAU=["ha"], # Deprecated
    # HBS=["sh"], # Deprecated
    HIN=["hi-IN"],
    # HYE=["hy"],
    IND=["id-ID"],
    JAV=["jv-ID"],
    JPN=["ja-JP"],
    # KAT=["ka-GE"],
    # KAZ=["kk-KZ"],
    # KIR=["ky-KG"],
    KOR=["ko-KR"],
    # KUR=["ku"], # Deprecated
    LAO=["lo-LA"],
    LIT=["lt-LT"],
    # LUO=[],
    MKD=["mk-MK"],
    MYA=["my-MM"],
    NAN=["nan-TW", "zh-CN"],
    # NDE=["nd"],
    # ORM=["om"],
    # PAN=["pa-IN"],
    PES=["fa-IR"],
    POL=["pl-PL"],
    POR=["pt-BR", "pt-PT"],
    # PRS=["prs-AF"],
    # PUS=["pa-AF"],
    RON=["ro-RO", "ro-MD"],
    # RUN=[],
    RUS=["ru-RU"],
    SLK=["sk-SK"],
    # SNA=["sn"],
    # SOM=["so-SO"],
    SPA=["es-US", "es-MX", "es-AR", "es-BO", "es-CL", "es-CO", "es-CR", "es-CU",
         "es-DO", "es-EC", "es-SV", "es-GQ", "es-GT", "es-HN", "es-NI", "es-PA",
         "es-PY", "es-PE", "es-PR", "es-ES", "es-UY", "es-VE"],
    # SQI=["sq-AL"],
    SWA=["sw-KE", "sw-TZ"],
    TAM=["ta-IN"],
    # TAT=[],
    # TGK=["tg-TJ"],
    # TGL=["tl-PH"],
    THA=["th-TH"],
    # TIR=[],
    # TPI=["tpi-PG"],
    TUR=["tr-TR"],
    UKR=["uk-UA"],
    # URD=["ur-IN"],
    UZB=["uz-UZ"],
    VIE=["vi-VN"],
    YUE=["yue-CN", "zh-CN"],
    ZUL=["zu-ZA"]
)