#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2025 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2025 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

FROM vllm/vllm-openai:latest

USER root

RUN apt-get update; \
    apt-get -y install curl ca-certificates python3-venv python3-pip python3-certifi python3-urllib3

RUN pip install huggingface_hub[cli]

ARG VLLM_MODEL="Qwen/Qwen3-30B-A3B-Instruct-2507-FP8"
ENV VLLM_MODEL="${VLLM_MODEL}"
RUN huggingface-cli download ${VLLM_MODEL}

# default value
ENV MAX_MODEL_LEN=45000

COPY --chown=root:root docker/vllm-entrypoint.sh /usr/bin/

ENTRYPOINT ["/usr/bin/vllm-entrypoint.sh"]

CMD [ \
    "--host", "0.0.0.0",\
    "--port", "11434",\
    ]