FROM vllm/vllm-openai:latest

USER root

RUN apt-get update; \
    apt-get -y install curl ca-certificates python3-venv python3-pip python3-certifi python3-urllib3

RUN pip install huggingface_hub[cli]

ARG VLLM_MODEL="Qwen/Qwen3-30B-A3B-Instruct-2507-FP8"
ENV VLLM_MODEL="${VLLM_MODEL}"
RUN huggingface-cli download ${VLLM_MODEL}

COPY --chown=root:root docker/vllm-entrypoint.sh /usr/bin/

ENTRYPOINT ["/usr/bin/vllm-entrypoint.sh"]

# recommended command for 40GB card
CMD [ \
    "--host", "0.0.0.0",\
    "--port", "11434",\
    "--max-model-len", "45000"\
    ]