#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2025 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2025 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

import os
if not os.environ.get("HF_HUB_OFFLINE"): os.environ["HF_HUB_OFFLINE"] = "0"
from llm_speech_summarization_component.llm_speech_summarization_component import run_component_test

class FakeClass():
    def __enter__(self):
        return self
    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type:
            print(f"An exception occurred: {exc_value}")
        return None 
    def __init__(self, **kwargs):
        for k,v in kwargs.items():
            self.__dict__[k] = v

# FakeLLM is a factory that returns an instance where .chat.completions.create is a function with kwargs
# When that function is called, return an array of event-like instances, regardless of arguments
FakeLLM = lambda: FakeClass(chat = FakeClass(completions=FakeClass(create=lambda  *_args, **_kwargs: [ \
            FakeClass(choices=[FakeClass(finish_reason=None, \
                                 delta=FakeClass(content="""{
  "summary": "The conversation is primarily centered on Major League Baseball, with a strong emphasis on historical and strategic aspects of the game. It includes detailed discussions of professional teams (e.g., New York Giants, Metropolitans, St. Louis), players (e.g., John J. Troy, Amos Rusie, Hugh Duffy, Dave Foutz, Arlie Latham), stadiums (e.g., Polo Grounds), and game-day practices such as pitching mechanics, base running, defensive positioning, and rule interpretations. Recurring themes include player development, mental and physical conditioning, team discipline, and the cultural legacy of early baseball. While some segments contain fragmented or unrelated content—such as business listings, real estate advertisements, restaurant promotions, and archival records—the dominant and consistent thread across all utterances is Major League Baseball, particularly its historical evolution, player behavior, and fan engagement. The presence of specific items of interest like baseball fields, teams, players, bats, hats, and balls reinforces this classification. The conversation reflects a deep engagement with the game’s tactical nuances, historical context, and the personal and professional lives of early baseball pioneers.",
  "primary_topic": "Major League Baseball",
  "other_topics": [
    "Player development and skill acquisition in professional baseball",
    "Baseball defensive strategies and player techniques",
    "Baseball rules and playing strategies",
    "Baseball player health and conditioning",
    "Team discipline and accountability",
    "Impact of alcohol on team performance",
    "Fan attendance and game-day atmosphere",
    "Historical context and evolution of baseball rules and styles",
    "Psychological and tactical aspects of player performance",
    "Infield and outfield positioning and defensive responsibilities",
    "Historical and cultural aspects of Major League Baseball",
    "Baseball strategy and player performance",
    "Fan culture and historical attendance",
    "Baseball-related traditions and rituals",
    "Business or property contact information",
    "Promotional content for food and dining",
    "Tailoring and retail services",
    "Distillery and Whiskey Production",
    "The role of newspapers and reporters in sports coverage",
    "Improvements in player performance due to fair scoring",
    "Branded products and names",
    "Cigars",
    "Champagne",
    "Wine",
    "Advertising signage or public announcements",
    "Location and construction details",
    "Business and real estate advertisements",
    "Distribution channels for luxury goods",
    "Import regulations and duties",
    "Historical marketing language",
    "Political or legal representation",
    "Construction industry",
    "Professional networking events",
    "Historical or commercial establishment in New York City",
    "Transcription errors or unintelligible speech",
    "Geographic locations and addresses in New York City",
    "Automotive sales advertisement",
    "Sports figures",
    "Vehicle listings",
    "Film production details",
    "Historical financial documents or archival text",
    "Names and individuals",
    "Insurance and financial institutions",
    "Urban infrastructure and street addresses",
    "Commercial enterprises in New York City",
    "Banking and brokerage services"
  ],
  "classifiers": [
    {
      "classifier": "Major League Baseball",
      "confidence": 0.95,
      "reasoning": "The conversation consistently references Major League Baseball through detailed discussions of professional teams (e.g., New York Giants, Metropolitans, St. Louis), players (e.g., John J. Troy, Amos Rusie, Hugh Duffy, Dave Foutz, Arlie Latham), stadiums (e.g., Polo Grounds), and historical games. It includes specific items of interest such as baseball fields, baseball teams, baseball players, baseball bats, baseball hats, and baseballs. The thematic focus on player development, strategic gameplay, team discipline, and historical evolution confirms the relevance of this classifier. Despite some fragmented or unrelated content about businesses, real estate, and restaurants in New York City, the core of the conversation remains firmly rooted in Major League Baseball. The high confidence is supported by the repeated and detailed engagement with baseball-specific terminology, historical figures, and game mechanics."
    }
  ],
  "entities": {
    "names_of_people": [
      "John J. Troy",
      "Freddie Engel",
      "Jacob Ruppert",
      "T. L. Huston",
      "W. A. Sunday",
      "Harry Stevens",
      "Nicholas Engel",
      "Lewis P. Fluhher",
      "McDermott & Hanigan",
      "Candler Bungie",
      "H. L. Sparrow",
      "W. N. Fleischmann",
      "W. E. Donovan",
      "Gabby",
      "Kling",
      "Street",
      "Amos Rusie",
      "Hugh Duffy",
      "Dad Clarke",
      "Johnny Ward",
      "J",
      "Mike Tiernan",
      "Jerry Denny",
      "Billy Nash",
      "Jimmy Collins",
      "Albert Mundorf",
      "James W.",
      "Mr. Lane",
      "Jim Mutrie",
      "John B. Day",
      "Jim",
      "the Chief",
      "Big Chief Roseman",
      "Mutrie Jim",
      "Tom Bolen",
      "Ralph Moore",
      "M. J. Leonard",
      "Arlie Latham",
      "Dave Foutz",
      "Chris Von der Ahe",
      "Charley Comiskey",
      "Mutrie",
      "Big Chief Roseman",
      "John L. Sullivan",
      "Billy Newman",
      "Bill Devery",
      "Jim",
      "McGinnis",
      "ARTHUR",
      "Chas H. Nahmmacher",
      "Brueks",
      "Me te",
      "E. F. Pierce",
      "M. L. Waish",
      "Frank Sparling",
      "HUSSEY’S CAFE",
      "Greeley",
      "Edward Healey",
      "Jas. Broderick",
      "Bob Reilly",
      "Jac. Philippi",
      "H. W. McIntyre",
      "Jos. J. oran",
      "Edward S. McGrath",
      "Sam Fitzpatrick",
      "Dick Butler",
      "James F. McCaffrey",
      "Howard Crampton",
      "Stewart Paton",
      "Ferdinand Strauss",
      "Louis T. McClenan"
    ],
    "places": [
      "New York City",
      "2774 Eighth Avenue, New York City",
      "1402 Broadway, Room 632, New York",
      "30 East 42nd Street, New York",
      "Polo Grounds",
      "Paterson, N. J.",
      "Postal Telegraph Building, 253 Broadway, New York",
      "Terminal Building",
      "103 Park Avenue, New York",
      "220 West 42nd Street, New York",
      "Boston",
      "Brotherhood Baseball Park",
      "home plate",
      "the diamond",
      "the outfield",
      "shortstop",
      "first base",
      "the grandstand",
      "the player’s bench",
      "the bar and lunch privilege at the grounds",
      "Harlem",
      "Eighth Avenue",
      "132nd Street",
      "125th Street",
      "133rd Street",
      "Manhattan Borough",
      "129th Street",
      "Harlem River",
      "156th Street",
      "Old Broadway",
      "5 Main Office",
      "136 Liberty Street",
      "Rector",
      "414-416-418 W. 14th Street",
      "419 West 13th Street",
      "S. W. Cor. 53rd St.",
      "8th Ave.",
      "HILL'S COLONIAL SANITARIUM Hotel",
      "Game CAFE",
      "125th Street and Eighth Ave.",
      "317 West 136th Street",
      "West 125th Street",
      "Morningside",
      "Chelsea",
      "13th Ave. and 30th St.",
      "B’way",
      "West 46th St.",
      "Columbus",
      "St. Louis",
      "the plate",
      "the coaching line",
      "Fulton Street",
      "231 Fulton Street",
      "50 Main Street 3 Rey Gs",
      "FLUSHING N.Y.",
      "Southeast Cor. 34th Street",
      "474 Eighth Ave",
      "123 St. and Eighth Avenue",
      "HOTEL MONTROSE",
      "2591 Eighth Avenue",
      "Audubon",
      "138th St. New York",
      "Third Ave. New York",
      "2268 Third Ave. New York",
      "2270 Third Ave. New York",
      "123d and 124th Streets",
      "West Side of Ave.",
      "Baltimore, MD",
      "Clinton St.",
      "Third and Fourth Ave’s",
      "First St.",
      "Washington and Beach Sts.",
      "2525 Eighth Avenue",
      "2546 Eighth Avenue",
      "135th Street",
      "Urbana",
      "Second Avenue",
      "1235 Second Avenue",
      "first-class hotels",
      "restaurants",
      "cafes",
      "12 Bridge St., New York",
      "Sixth Avenue",
      "Tenth Street",
      "Stuyvesant",
      "622 St. Nicholas Ave",
      "759 Seventh Avenue",
      "50th Street",
      "Cor. 50th Street",
      "Cor. Sist Street",
      "McDERMOTT| Bohan & DAIRY CO. | O’Beirne",
      "2425 8tu Ave.",
      "Spring",
      "General Office",
      "49th Street",
      "8th Avenue",
      "Morningside Avenue",
      "Cavanaugh",
      "CArr S. E. Cor.",
      "47th and 48th Street",
      "110 West 52nd Street",
      "6th and 7th Aves.",
      "GS",
      "128 Broadway",
      "Providence",
      "Chicago",
      "Toronto",
      "Detroit",
      "Springfield",
      "Philadelphia",
      "Worcester",
      "41 Broad Street",
      "24-26 Vandewater Street",
      "Library of Congress"
    ],
    "companies": [
      "Troy & Engel",
      "Nicholas Engel - Cast-Iron Gas and Water Pipe",
      "Lewis P. Fluhher Company",
      "McDermott & Hanigan",
      "Candler Bungie",
      "American League Baseball Club of New York",
      "Daniel Devan & Co.",
      "Fay's",
      "William J. Howe Co.",
      "Audubon",
      "Haight & Todd",
      "Jersey Real Estate",
      "A. SILZ BASEBALL Incorporated",
      "Albert Mundorf, Prop.",
      "Gallagher CAFE",
      "Daniel Brothers",
      "Clover Valley Print",
      "H. Schwabeland",
      "TOM Butter, Eggs & Cheese",
      "Harlem’s Favorite Hotel",
      "Ruppert’s",
      "Geo. Ehret’s",
      "Old English Chop House",
      "SPARLING’S Storage Warehouse",
      "Chatham SELEcTED Clams",
      "Cartwright & Co.",
      "Jos. J. oran",
      "H. W. McIntyre",
      "McGRORTY’S",
      "Distillers & Curers of RYE WHISKIES",
      "Morningside",
      "Urbana Wine Co.",
      "Gold Seal",
      "America’s Best",
      "Sayles, Zahn Company",
      "Butchers & Packers",
      "CAFE Contractors",
      "Business Men’s Lunch",
      "Carstairs Whiskey",
      "B. &",
      "Pilsner Beer",
      "CORD",
      "New and Used Cars Sold CORD",
      "Brokers in All Makes",
      "CA FE",
      "NEW and USED AUTONOBILES 711 7th Ave.",
      "Universal Film Co.",
      "BRYANT",
      "Equitable Life Assurance Society of the United States",
      "Chas. A. Stoneham & Company",
      "McDermott Printing Company, Inc."
    ],
    "body_parts": [
      "eyesight",
      "brain",
      "arm",
      "throwing arm",
      "muscular development",
      "left foot",
      "right foot",
      "shoulder",
      "hand",
      "eyes",
      "wrists",
      "hip",
      "feet",
      "base line",
      "plate",
      "bat",
      "hips",
      "shoulder",
      "elbow",
      "knee joints",
      "ankles",
      "bowels",
      "sinews",
      "blood",
      "pair of scissors"
    ],
    "emotions": [
      "enthusiasm",
      "gratitude",
      "respect",
      "nostalgia",
      "discouraged",
      "encouraged",
      "rattled",
      "confidence",
      "doubt",
      "happiness",
      "frustration",
      "anxious",
      "timid",
      "revitalization",
      "competitive spirit",
      "disconnection",
      "strangeness",
      "uneasy",
      "lost his head",
      "delight",
      "admiration",
      "enthusiasm"
    ]
  }
}"""))], object="chat.completion.chunk"), \
            FakeClass(choices=[FakeClass(finish_reason=True)]), \
        ])))

def test_invocation_with_fake_client():
    result = run_component_test(FakeLLM)
    assert len(result) == 2
    main_detection = result[0]
    classifier_detection = result[1]
    assert main_detection.detection_properties['TEXT'] == "The conversation is a composite of reflective, instructional, and historical narratives centered on early professional baseball, particularly focusing on the New York Metropolitans and the broader context of Major League Baseball in the 19th and early 20th centuries. It emphasizes player development, physical conditioning, strategic gameplay, and team discipline, drawing on personal anecdotes, historical accounts, and critiques of evolving rules and practices. The discourse includes detailed discussions on batting mechanics, defensive positioning, base running, and the psychological aspects of competition, often referencing legendary players and managers like Jim Mutrie, Amos Rusie, and Dad Clarke. While some segments contain fragmented or unrelated business listings and advertisements, the dominant thread remains a deep engagement with the sport’s history, culture, and professional standards."
    assert classifier_detection.detection_properties['CLASSIFIER'] == 'Major League Baseball'
    assert classifier_detection.confidence == 0.98